# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eddaed109db0dd765752b3c9dd5919e26c1ec5295eeeb49e121326c8973a9b472710b1fd8a202d6f58e1e3e7667f5fc22da0355f361656a132659c3a3d653f09

test:
  secret_key_base: 9fc8dcb653bc89be02cae02c8f1d3a94202e467571d0a444ed12e79998d88b99e14bb25f30bc12e917d64ebf79963dd6c1ace16cfc4d4a7d36645e16025d7293

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
